version: '3.8'
services:
  source-db:
    image: "nerudista/dvdrental:latest"
    container_name: source-db-container
    ports:
      - "5432:5432"
    volumes:
      - source-db-volume:/var/lib/postgresql/data
      - source-scripts-volume:/home/biuser/scripts
  dest-db:
    image: "nerudista/dvdrental_dwh:latest"
    container_name: dest-db-container
    ports:
      - "5434:5432"
    volumes:
      - dest-db-volume:/var/lib/postgresql/data
      - dest-scripts-volume:/home/biuser/scripts
volumes:
  source-db-volume:
  source-scripts-volume:
  dest-db-volume:
  dest-scripts-volume: